package:
  name: gff-toolbox
  version: 0.1_alpha

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - processrcmfolder = uconnrcmpy.dataprocessing:process_folder


requirements:
  build:
    - python >=3.7,{{PY_VER}}*
    - setuptools

  run:
    - python {{PY_VER}}*
    - setuptools
    - setuptools-git
    - pandas
    - biopython==1.78
    - docopt
    - pprintpp
    - bcbio-gff
    - matplotlib
    - pymongo
    - dna_features_viewer
    - mongodb

channels:
  - anaconda
  - conda-forge
  - bioconda

about:
  home: https://github.com/fmalmeida/gff-toolbox
