package:
  name: gff-toolbox
  version: 0.3

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - processrcmfolder = uconnrcmpy.dataprocessing:process_folder


requirements:
  build:
    - python >=3.7,{{PY_VER}}*
    - setuptools
    - setuptools-git
    - pandas
    - biopython==1.78
    - docopt
    - pprintpp
    - bcbio-gff
    - matplotlib
    - pymongo
    - dna_features_viewer
    - mongodb
    - pyfaidx
    - bioconductor-karyoploter
    - bioconductor-rtracklayer
    - bioconductor-genomicranges
    - bioconductor-plyranges
    - r-dplyr
    - r
    - r-base
    - r-docopt

  run:
    - python {{PY_VER}}*
    - setuptools
    - setuptools-git
    - pandas
    - biopython==1.78
    - docopt
    - pprintpp
    - bcbio-gff
    - matplotlib
    - pymongo
    - dna_features_viewer
    - mongodb
    - pyfaidx
    - bioconductor-karyoploter
    - bioconductor-rtracklayer
    - bioconductor-genomicranges
    - bioconductor-plyranges
    - r-dplyr
    - r
    - r-base
    - r-docopt

channels:
  - defaults
  - anaconda
  - conda-forge
  - bioconda
  - r

about:
  home: https://github.com/fmalmeida/gff-toolbox
